version: '3.8'
services:
  backend:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
  db:
    container_name: pg_container
    image: postgres:15.3-alpine3.18
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=awesomestack
    ports:
      - '5432:5432'
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
