version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres:15.3-alpine3.18
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - '5430:5432'
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
